fix

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -28,11 +28,9 @@ jobs:
           exit 1
         fi
 
-        # Verzeichnis erstellen, falls nicht vorhanden
         LOG_DIR="./logs"
         mkdir -p $LOG_DIR
 
-        # Log-Datei erstellen und Ausgaben mit tee aufzeichnen
         ./publish/linux/ServerNetworkAPI --headless --nmap $LOG_DIR/run120.log 2>&1 | tee $LOG_DIR/run120.log &
         PID=$!
         echo "Started with PID $PID"
@@ -45,16 +43,11 @@ jobs:
           echo "Sent SIGINT to process"
         else
           echo "::error ::Process $PID already exited. Probably crashed."
-          cat $LOG_DIR/run120.log
+          cat run120.log
           exit 1
         fi
 
     - name: Show full log of run120.log
       run: |
-        # Überprüfen, ob die Log-Datei existiert
-        if [ -f $LOG_DIR/run120.log ]; then
-          echo "========== FULL LOG: run120.log =========="
-          cat $LOG_DIR/run120.log
-        else
-          echo "run120.log not found."
-        fi
+        echo "========== FULL LOG: run120.log =========="
+        cat run120.log || echo "run120.log not found."
